### ISSUE TITLE
Should we be advocating the use of the new tests schema?

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint-rule-tester#9]
@davidtheclark All the stylelint rules have been ported over to the new tests schema and it's a joy to use. 

Should we be advocating the same for plugins e.g. [`stylelint-selector-bem-pattern`](https://github.com/davidtheclark/stylelint-selector-bem-pattern/blob/master/test/index.js)? I'm thinking it's worth getting this right now as more people are starting to write plugins for stylelint.

If so, would a new version of this rule-tester be needed?

**Comment by davidtheclark** [comment]
Yes, I believe we should advocate this instead: https://github.com/stylelint/stylelint-test-rule-tape.

I will try to remember to switch over that existing plugin. If you want to do it or create an issue, feel free!

**Comment by jeddy3** [comment]
> Yes, I believe we should advocate this instead:

Should we deprecate this module then?

> If you want to do it or create an issue, feel free!

Would the codemod you wrote work on `stylelint-selector-bem-pattern` too? If so, is it worth making it available for other plugin authors to use if this module gets deprecated?

**Comment by davidtheclark** [comment]
stylelint-selector-bem-pattern now uses stylelint-test-rule-tape.

I do not think the codemod will be very useful outside our codebase, because it took advantages of conventions we had that would not be universal. I do not think anybody should have a hard time converting plugins over, though.

**Comment by jeddy3** [comment]
> stylelint-selector-bem-pattern now uses stylelint-test-rule-tape.

Looks great!

> I do not think anybody should have a hard time converting plugins over, though.

Agreed.

Shall we deprecate this module now? Is that just the case of:

1. Running `npm deprecate stylelint-rule-tester "Use stylelint-test-rule-tape instead"`
2. Adding "**Deprecated: use stylelint-test-rule-tape instead**" to the top of the README?

**Comment by davidtheclark** [comment]
Yeah, that's the process. Feel free or I will get to it later.

**Comment by davidtheclark** [comment]
Ok, I deprecated.
